### GET request to tasks API root
GET localhost:8000/api/tasks/

### POST request creating a test task
POST localhost:8000/api/tasks/
Content-Type: application/json

{
    "name": "Test task!"
}

### GET request on non-existent object
GET localhost:8000/api/tasks/9999
